### ISSUE TITLE
Alterações nos textos da seção sobre "o que é a hacktoberfest"

### ISSUE THREAD

**Issue by levxyca** [levxyca/hacktoberfest#11]
### Alteração nos textos

- Alterar a cor de todos os textos dessa parte para `#FAFAFA`

Se atente a utilizar as classes já existentes no HTML ou criar novas seguindo o padrão 😊

![Exemplo](https://user-images.githubusercontent.com/19956731/136047787-ebe3d48e-ffe7-4675-a7c4-2da24f8bb03f.png)

**Comment by rpradosilva** [comment]
Posso contribuir com esta issue?

**Comment by rpradosilva** [comment]
PR enviada [https://github.com/levxyca/hacktoberfest/pull/13](https://github.com/levxyca/hacktoberfest/pull/13)
