### ISSUE TITLE
Ajustando parágrafo da seção "o que é a hacktoberfest"

### ISSUE THREAD

**Issue by levxyca** [levxyca/hacktoberfest#12]
### Ajustando parágrafo

- Adicione uma margem dos lados do parágrafo de `5rem` e para cima e baixo `1.5rem`
- Espaçamento entre as linhas de `1.2rem`

Se atente a utilizar as classes já existentes no HTML ou criar novas seguindo o padrão 😊

![Exemplo](https://user-images.githubusercontent.com/19956731/136048309-ec498d5e-a8ac-4756-9b9c-b1bf1d9e8d52.png)

**Comment by rpradosilva** [comment]
Gostaria de contribuir com esta também, posso?

**Comment by rpradosilva** [comment]
Acabei ajustando o espaçamento entre linhas: https://github.com/levxyca/hacktoberfest/pull/14
