### ISSUE TITLE
Modificando o título principal do site

### ISSUE THREAD

**Issue by levxyca** [levxyca/hacktoberfest#2]
### Essa issue consiste em fazer as seguintes modificações no título principal do site:

O título é o nosso `h1` dentro da tag `header`.

- Alterar o o tamanho da fonte para `2.5rem`
- Adicionar um espaçamento entre as letras de `.1em`
- Deixar o texto todo minúsculo
- A cor do texto deve ser `#FAFAFA` 

Se atente a utilizar as classes já existentes no HTML ou criar novas seguindo o padrão 😊

**Comment by vduggen** [comment]
Teria como atribuir isto para mim?
