### ISSUE TITLE
Alterações no menu

### ISSUE THREAD

**Issue by levxyca** [levxyca/hacktoberfest#3]
### Adicionando propriedades novas no menu do site:

O menu do site é o que se encontra na página inicial, logo abaixo do nosso título! Esse PR deve conter as seguintes alterações:

- Cor do texto deve ser `#FAFAFA`
- A fonte com tamanho `1rem`
- Um espaçamento entre um item do menu e outro. O espaçamento por ser de sua preferência.

Se atente a utilizar as classes já existentes no HTML ou criar novas seguindo o padrão 😊

**Comment by vduggen** [comment]
Teria como me atribuir?
