### ISSUE TITLE
Redirecionamento para o artigo no README

### ISSUE THREAD

**Issue by vduggen** [levxyca/hacktoberfest#6]
Estou curioso para ler sobre o artigo que originou esse projeto, achei em outro lugar o artigo porém se tiver como arrumar o redirecionamento para o artigo. Até pensei em abrir um PR, porém não sabia se o mesmo artigo que eu achei era esse o mesmo que você queria redirecionar.

**Comment by levxyca** [comment]
Obrigada pelo feedback! Eu realmente coloquei o link errado! Caso queira abrir o PR esse é o link do artigo: https://dev.to/levxyca/inicie-no-mundo-open-source-participando-da-hacktoberfest-3np6
